%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-launch-testing
Version:        3.9.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS launch_testing package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-pytest
Requires:       ros-rolling-ament-index-python
Requires:       ros-rolling-launch
Requires:       ros-rolling-launch-xml
Requires:       ros-rolling-launch-yaml
Requires:       ros-rolling-osrf-pycommon
Requires:       ros-rolling-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-copyright
BuildRequires:  ros-rolling-ament-flake8
BuildRequires:  ros-rolling-ament-pep257
BuildRequires:  ros-rolling-ament-xmllint
%endif

%description
A package to create tests which involve launch files and multiple processes.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Thu Apr 24 2025 Aditya Pande <aditya.pande@openrobotics.org> - 3.9.0-1
- Autogenerated by Bloom

* Fri Apr 18 2025 Aditya Pande <aditya.pande@openrobotics.org> - 3.8.1-1
- Autogenerated by Bloom

* Thu Feb 27 2025 Aditya Pande <aditya.pande@openrobotics.org> - 3.8.0-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.7.1-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.7.0-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.6.1-1
- Autogenerated by Bloom

* Tue Jun 25 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.6.0-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.5.1-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.5.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.4.2-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.4.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Aditya Pande <aditya.pande@openrobotics.org> - 3.4.0-2
- Autogenerated by Bloom

